# 环境配置
env:
  basePath: /opt/.heluox
  java:
    version: "17"
    home: "/usr/lib/jvm/java-17-openjdk-17.0.15.0.6-2.el9.aarch64"

# 服务元数据
service:
  name: "heluox-agent"
  displayName: "heluox主机代理服务"
  version: "v1.0"
  port:
    - 8080
    - 18080
  param:
    jvmOpts: "-Xms2048m -Xmx2048m"
    mainArgs: ""
  path:
    artifactFile: "/opt/.heluox/repository/java/heluox-agent/v1/heluox-agent.jar"
    installDir: ""
    logDir: ""
  healthCheck:
    httpGet:
      port: 8401
      path: "/test"
      scheme: HTTP
    timeoutSeconds: 30                 # 超时时间
    periodSeconds: 5                   # 检测间隔
    successThreshold: 1                # 检查成功为 1 次表示就绪
    failureThreshold: 2                # 检测失败 2 次表示未就绪