# 环境配置
env:
  java:
    version: "1.8"
    home: "/usr/lib/jvm/java-1.8.0-openjdk"

# 服务元数据
service:
  name: "example-server"
  displayName: "示例服务"
  version: "v1.0"
  port:
    - 8080
    - 18080
  param:
    jvmOpts: "-Xms2048m -Xmx2048m"
    mainArgs: "test=true"
  path:
    artifactFile: "/opt/data/example-server.jar"
    installDir: "/opt/"
    logDir: "/opt/logs/"
  healthCheck:
    httpGet:
      port: 8080
      path: "/actuator/health"
      scheme: HTTP
    initialDelaySeconds: 10            # 初始化时间, 健康检查延迟执行时间
    timeoutSeconds: 30                 # 超时时间
    periodSeconds: 5                   # 检测间隔
    successThreshold: 1                # 检查成功为 1 次表示就绪
    failureThreshold: 2                # 检测失败 2 次表示未就绪