---
- name: 设置候选Java路径列表
  set_fact:
    candidate_java_homes: |
      {{
        ( [env.java.home] if env.java.home is defined else [] ) +
        ( [ansible_facts.env.JAVA_HOME] if ansible_facts.env.JAVA_HOME is defined else [] ) +
        [
          '/usr/lib/jvm/java-' + env.java.version + '-openjdk',
          '/usr/lib/jvm/jdk-' + env.java.version,
          '/usr/java/jdk' + env.java.version,
          '/usr/local/java/jdk' + env.java.version,
          '/opt/java/jdk' + env.java.version
        ]
      }}

- name: 检查候选路径是否存在
  stat:
    path: "{{ java_path }}/bin/java"
  register: java_path_checks
  loop: "{{ candidate_java_homes }}"
  loop_control:
    loop_var: java_path
  ignore_errors: yes

- name: 提取有效的候选路径
  set_fact:
    valid_java_homes: "{{ java_path_checks.results | selectattr('stat.exists') | map(attribute='java_path') | list }}"

- name: 验证Java安装
  block:
    - name: 测试候选Java版本
      command: "{{ java_home }}/bin/java -version"
      register: java_test
      changed_when: false
      ignore_errors: yes
      loop: "{{ valid_java_homes }}"
      loop_control:
        loop_var: java_home
    
    - name: 提取匹配版本的有效路径
      set_fact:
        effective_java_home: "{{ result.java_home }}"
        java_version: >-
          {% set version_lines = result.stderr.split('\n') | default([]) %}
          {% for line in version_lines %}
            {% if 'version' in line %}
              {{ line.split('"')[1] | default('unknown') }}
            {% endif %}
          {% endfor %}
      when: 
        - not result.failed
        - result.stderr is defined
        - (' version "' + env.java.version + '.') in result.stderr
      loop: "{{ java_test.results }}"
      loop_control:
        loop_var: result
  
- name: 验证Java安装结果
  assert:
    that:
      - effective_java_home is defined
      - java_version != 'unknown'
    fail_msg: |
      未找到有效的Java {{ env.java.version }} 安装！
      已检查路径:
      {% for path in candidate_java_homes %}
        - {{ path }}
      {% endfor %}
      有效路径:
      {% for path in valid_java_homes %}
        - {{ path }}
      {% endfor %}
      请确保已安装正确版本的JDK
    success_msg: "Java验证通过: {{ effective_java_home }} (版本: {{ java_version }})"