---
- name: 检查必需参数不为空
  assert:
    that:
      - env is defined and env
      - env.basePath is defined and env.basePath | length > 0
      - env.java is defined and env.java
      - env.java.version is defined and env.java.version | length > 0
      - env.java.home is defined and env.java.home | length > 0
      - service is defined and service
      - service.name is defined and service.name | length > 0
      - service.displayName is defined and service.displayName | length > 0
      - service.version is defined and service.version | length > 0
      - service.port is defined and service.port | length > 0
      - service.param is defined and service.param
      - service.param.jvmOpts is defined and service.param.jvmOpts | length > 0
      - service.path is defined and service.path
      - service.path.repoFile is defined and service.path.repoFile | length > 0
    msg: "必需参数不能为空"

- name: 检查端口参数有效性
  assert:
    that:
      - port_item is match('^[0-9]+/(TCP|UDP)$')
      - port_item.split('/')[0] | int >= 1
      - port_item.split('/')[0] | int <= 65535
    msg: "端口格式必须为'端口号/TCP'或'端口号/UDP'，且端口号在1-65535之间"
  loop: "{{ service.port }}"
  loop_control:
    loop_var: port_item