# 安装
- hosts: all
  roles:
  - role: env_check
    # - role: deploy_prepare
    # - role: start
  tags: 
    - install

# # 更新
# - hosts: all
#   serial: 1  # 滚动更新
#   roles:
#     - role: stop
#     - role: cleanup
#     - role: deploy_prepare
#     - role: start
#   tags: 
#     - update

# # 启动
# - hosts: all
#   roles:
#     - role: start
#   tags: 
#     - start

# # 停止
# - hosts: all
#   roles:
#     - role: stop
#   tags: 
#     - stop

# # 重启
# - hosts: all
#   serial: 1  # 滚动重启
#   roles:
#     - role: stop
#     - role: start
#   tags: 
#     - restart

# # 重启
# - hosts: all
#   roles:
#     - role: statusCheck
#   tags: 
#     - statusCheck

# # 卸载
# - hosts: all
#   roles:
#     - role: stop
#     - role: cleanup
#   tags: 
#     - uninstall

