- hosts: all
  tasks:
    - name: param check
      include_role:
        name: check_param

    - name: system check
      include_role:
        name: check_env
        tasks_from: system_check.yml

    - name: start
      include_role:
        name: start