# 滚动更新
- hosts: all
  serial: 1
  tasks:
    - name: param check
      include_role:
        name: check_param

    - name: stop
      include_role:
        name: stop
      ignore_errors: yes

    - name: cleanup
      include_role:
        name: cleanup

    - name: env check
      include_role:
        name: check_env

    - name: build
      include_role:
        name: build

    - name: start
      include_role:
        name: start