---
- name: 验证JDK安装目录
  block:
    - name: 检查JDK安装目录是否存在
      stat:
        path: "{{ env.java.home }}"
      register: java_home_stat

    - name: 断言目录有效性
      assert:
        that:
          - java_home_stat.stat.exists
          - java_home_stat.stat.isdir
        fail_msg: "JDK安装目录无效: {{ env.java.home }} (必须存在且是目录)"
        success_msg: "JDK安装目录验证通过: {{ env.java.home }}"

- name: 验证Java可执行文件
  block:
    - name: 检查java可执行文件
      stat:
        path: "{{ env.java.home }}/bin/java"
      register: java_exec_stat

    - name: 断言可执行文件有效性
      assert:
        that:
          - java_exec_stat.stat.exists
          - java_exec_stat.stat.isreg
          - (java_exec_stat.stat.mode | int) & 0o111 != 0  # 位运算检查执行权限
        fail_msg: |
          Java可执行文件验证失败: {{ env.java.home }}/bin/java
          可能原因:
          1. 文件不存在
          2. 不是常规文件
          3. 缺少执行权限 (当前权限: {{ java_exec_stat.stat.mode | oct }})
        success_msg: "Java可执行文件验证通过: {{ env.java.home }}/bin/java"

- name: 检查Java版本
  block:
    - name: 获取Java版本信息
      command: "{{ env.java.home }}/bin/java -version"
      register: java_version_check
      changed_when: false
      ignore_errors: yes

    - name: 断言版本匹配
      assert:
        that:
          - not java_version_check.failed
          - java_version_check.stderr is regex('version "{{ env.java.version }}[\\\\.\\\\-]')
        success_msg: "Java版本验证通过 (要求: {{ env.java.version }}, 实际: {{ java_version_check.stderr | regex_search('version \"([0-9.]+)', '\\1') | first }})"
        fail_msg: |
          Java版本不匹配！
          要求版本: {{ env.java.version }}
          实际输出: {{ java_version_check.stderr | default('无版本信息') | trim }}
          可能原因:
          1. JAVA_HOME路径错误: {{ env.java.home }}
          2. 未安装JDK {{ env.java.version }}
          3. 环境变量未生效
  when: env.java.version is defined